TKN = "token"
CLIENT_CONNECTED = "client_connected"
CLIENT_CLOSED = "client_closed"
PLAYER_JOIN = "player_join"
PLAYER_UPDATE = "player_update"
PLAYER_INFO = "player_info"
PLAYER_ANSWER = "player_answer"
