# Form implementation generated from reading ui file 'd:\Desktop_Folders\SFU\Assignments\Summer 2022\CMPT 371\Project\ui\main_screen.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(700, 600)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 168, 119))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 168, 119))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 168, 119))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 168, 119))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 168, 119))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 168, 119))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush)
        Dialog.setPalette(palette)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.debugLabel = QtWidgets.QLabel(Dialog)
        self.debugLabel.setObjectName("debugLabel")
        self.verticalLayout.addWidget(self.debugLabel)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_0 = QtWidgets.QVBoxLayout()
        self.verticalLayout_0.setObjectName("verticalLayout_0")
        self.usernameLabel0 = QtWidgets.QLabel(Dialog)
        self.usernameLabel0.setStyleSheet("QLabel { \n"
"    color: white;\n"
"    font: 15pt \"Inter\";\n"
"    margin: 0px 10px;\n"
"}")
        self.usernameLabel0.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.usernameLabel0.setObjectName("usernameLabel0")
        self.verticalLayout_0.addWidget(self.usernameLabel0)
        self.scoreLabel0 = QtWidgets.QLabel(Dialog)
        self.scoreLabel0.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.scoreLabel0.setObjectName("scoreLabel0")
        self.verticalLayout_0.addWidget(self.scoreLabel0)
        self.horizontalLayout.addLayout(self.verticalLayout_0)
        self.verticalLayout_1 = QtWidgets.QVBoxLayout()
        self.verticalLayout_1.setObjectName("verticalLayout_1")
        self.usernameLabel1 = QtWidgets.QLabel(Dialog)
        self.usernameLabel1.setStyleSheet("QLabel { \n"
"    color: white;\n"
"    font: 15pt \"Inter\";\n"
"    margin: 0px 10px;\n"
"}")
        self.usernameLabel1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.usernameLabel1.setObjectName("usernameLabel1")
        self.verticalLayout_1.addWidget(self.usernameLabel1)
        self.scoreLabel1 = QtWidgets.QLabel(Dialog)
        self.scoreLabel1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.scoreLabel1.setObjectName("scoreLabel1")
        self.verticalLayout_1.addWidget(self.scoreLabel1)
        self.horizontalLayout.addLayout(self.verticalLayout_1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.usernameLabel2 = QtWidgets.QLabel(Dialog)
        self.usernameLabel2.setStyleSheet("QLabel { \n"
"    color: white;\n"
"    font: 15pt \"Inter\";\n"
"    margin: 0px 10px;\n"
"}")
        self.usernameLabel2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.usernameLabel2.setObjectName("usernameLabel2")
        self.verticalLayout_3.addWidget(self.usernameLabel2)
        self.scoreLabel2 = QtWidgets.QLabel(Dialog)
        self.scoreLabel2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.scoreLabel2.setObjectName("scoreLabel2")
        self.verticalLayout_3.addWidget(self.scoreLabel2)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.debugLabel.setText(_translate("Dialog", "TextLabel"))
        self.usernameLabel0.setText(_translate("Dialog", "usernameLabel0"))
        self.scoreLabel0.setText(_translate("Dialog", "score0"))
        self.usernameLabel1.setText(_translate("Dialog", "usernameLabel1"))
        self.scoreLabel1.setText(_translate("Dialog", "score1"))
        self.usernameLabel2.setText(_translate("Dialog", "usernameLabel2"))
        self.scoreLabel2.setText(_translate("Dialog", "score2"))
